#配置dev环境
spring:
  profiles: dev
  application:
    name: kkbmsc-eurekaServer-config

server:
  port: 7100

eureka:
  instance:
    hostname: eureka8400.com
    preferIpAddress: true
  client:
    register-with-eureka: false  #指定当前主机是否需要向注册中心注册(不用，因为当前主机就是server)
    fetch-registry: false        #指定当前主机是否需要获取注册信息(不需要，因为当前主机就是server)
    service-url:     #暴露服务中心地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false   #eureka自我保护开关不建议关闭

---
#配置test环境
spring:
  profiles: dev
  application:
    name: kkbmsc-eurekaServer-config

server:
  port: 7101

eureka:
  instance:
    hos
  hostname: eureka8500.com
    preferIpAddress: true
  client:
    register-with-eureka: false  #指定当前主机是否需要向注册中心注册(不用，因为当前主机就是server)
    fetch-registry: false        #指定当前主机是否需要获取注册信息(不需要，因为当前主机就是server)
    service-url:     #暴露服务中心地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false   #eureka自我保护开关不建议关闭